site_name: Clear-Directory
repo_url: https://github.com/jmuelbert/cleardirectory
theme: readthedocs
pages:
  - Home: index.md
  - Clean-Directory Basics:
    - What is Clean-Directory: about.md
    - Quick Start: Quick-Start-Installation-and-Example.md
  - Acknowledgements: acknowledgements.md
