# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by: Juergen Muelbert
# Generated on: 12.03.19

@{
    RootModule        = 'Clear-Directory.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = '475ee509-b052-4ab4-8f75-9cd793f84004'
    Author            = 'Juergen Muelbert'
    CompanyName       = 'Unknown'
    Copyright         = '(c) Juergen Muelbert. All rights reserved.'
    Description       = ''
    # Functions to export from this module
    FunctionsToExport = '*'

    # Cmdlets to export from this module
    CmdletsToExport = '*'

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module
    AliasesToExport = '*'
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}

